services:
  postgres:
    image: postgres:17-alpine
    container_name: skp-os-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: skp_os
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d skp_os"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data1:
